//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFootballWebsite.App_Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MyFootballDatabaseEntities1 : DbContext
    {
        public MyFootballDatabaseEntities1()
            : base("name=MyFootballDatabaseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Articles> tbl_Articles { get; set; }
        public virtual DbSet<tbl_Authors> tbl_Authors { get; set; }
    
        public virtual ObjectResult<GetHeadlineNews_Result> GetHeadlineNews()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHeadlineNews_Result>("GetHeadlineNews");
        }
    }
}
