//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFootballWebsite.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Articles
    {
        public int Id { get; set; }
        public string ArticleTitle { get; set; }
        public string ArticleContent { get; set; }
        public System.DateTime ArticleCreated { get; set; }
        public Nullable<int> ArticleSubmittedBy { get; set; }
    
        public virtual tbl_Authors tbl_Authors { get; set; }
    }
}
